linters:
  enable:
    - gofmt
    - revive
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - typecheck
    - bodyclose

linters-settings:
  gofmt:
    simplify: true
  revive:
    confidence: 0.8
  govet:
    check-shadowing: true

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor/

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - "should have comment"
    - "always nil"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true