name: Node.js Client CI

on:
  push:
    branches: [ main ]
    paths:
      - 'clients/nodejs/**'
      - '.github/workflows/nodejs.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'clients/nodejs/**'
      - '.github/workflows/nodejs.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clients/nodejs
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    
    - name: Install root dependencies
      run: npm ci
      working-directory: .
      
    - name: Install workspace dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Run tests
      run: npm run test
      
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./clients/nodejs/coverage/lcov.info
        fail_ci_if_error: true

  build:
    needs: test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: clients/nodejs
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    
    - name: Install root dependencies
      run: npm ci
      working-directory: .
      
    - name: Install workspace dependencies
      run: npm ci
      
    - name: Build package
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nodejs-client-dist
        path: clients/nodejs/dist/
        retention-days: 7
